name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/cs2d-serverlist
            git clean -fd
            git pull origin main
            npm install -g uglify-js uglifycss
            uglifyjs public/script.js -o public/script.js
            uglifycss public/style.css --output public/style.css
            npm install
            pm2 restart cs2d-serverlist
