name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install deployment tools
      - name: Setup deployment tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync

      # 3. Sync project files to VPS
      - name: Sync files to VPS
        env:
          VPS_HOST: ${{ secrets.SSH_HOST }}
          VPS_USER: ${{ secrets.SSH_USERNAME }}
          VPS_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASS" rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '*.log' \
            ./ $VPS_USER@$VPS_HOST:/home/$VPS_USER/cs2d-serverlist/

      # 4. Install dependencies, CS2D & minify CSS, then restart PM2
      - name: Install dependencies, CS2D & minify CSS
        env:
          VPS_HOST: ${{ secrets.SSH_HOST }}
          VPS_USER: ${{ secrets.SSH_USERNAME }}
          VPS_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASS" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            set -e
            cd /home/$USER/cs2d-serverlist

            echo "Installing npm dependencies..."
            npm ci --omit=dev

            # Install CS2D if missing
            if [ -z "$(ls -A ~/cs2d-serverlist/public/cs2d)" ]; then
              mkdir -p ~/cs2d-serverlist/public/cs2d
              curl -sSL https://gist.github.com/ernestpasnik/1fa721c2bf35a50d27ef13fd183882fb/raw | bash -s -- -d ~/cs2d-serverlist/public/cs2d
            fi

            # Minify CSS if exists
            if [ -f ~/cs2d-serverlist/public/css/main.css ]; then
              command -v uglifycss >/dev/null 2>&1 || npm install -g uglifycss
              uglifycss ~/cs2d-serverlist/public/css/main.css > ~/cs2d-serverlist/public/styles.css || true
              rm -rf ~/cs2d-serverlist/public/css || true
            fi

            echo "Restarting PM2 process via ecosystem file..."
            pm2 reload ecosystem.config.js --env production
          EOF
