name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # Upload files via SFTP
      - name: Deploy with SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}   # or ssh_private_key
          port: 22
          local_path: './'
          remote_path: /home/ubuntu/cs2d-serverlist/
          exclude: |
            .git*
            .github*
            node_modules/*
            .env
            public/cs2d/*

      # Run post-deploy commands
      - name: Install CS2D if missing & restart PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu/cs2d-serverlist

            # --- Install CS2D if missing ---
            if [ ! -x "public/cs2d/cs2d_dedicated" ]; then
              echo "Installing CS2D dedicated server..."

              sudo dpkg --add-architecture i386 || true
              sudo apt-get update -y
              sudo apt-get install -y curl unzip libstdc++6:i386

              ver=$(curl -s https://unrealsoftware.de/game_cs2d.php | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | sed 's/\.//g')
              cid=$(curl -s "https://unrealsoftware.de/get.php?get=cs2d_${ver}_linux.zip" | grep -m1 -o '"get.php[^"]*"' | cut -d'"' -f2 | sed 's/.*cid=//')

              curl -s "https://unrealsoftware.de/get.php?get=cs2d_${ver}_linux.zip&p=1&cid=${cid}" -o cs2d.zip
              curl -s "https://unrealsoftware.de/files_pub/cs2d_dedicated_linux.zip" -o cs2d_dedicated.zip

              mkdir -p public/cs2d
              unzip -qq -o cs2d.zip -d public/cs2d
              unzip -qq -o cs2d_dedicated.zip -d public/cs2d

              rm -rf cs2d.zip cs2d_dedicated.zip \
                     public/cs2d/help public/cs2d/logos public/cs2d/screens \
                     public/cs2d/gfx/fonts public/cs2d/sys/cache public/cs2d/sys/language

              chmod +x public/cs2d/cs2d_dedicated
              echo "✅ CS2D installed."
            else
              echo "CS2D already present. Skipping."
            fi

            # --- Minify CSS ---
            if ! command -v uglifycss >/dev/null; then
              sudo npm install -g uglifycss
            fi
            [ -f public/css/main.css ] && uglifycss public/css/main.css > public/styles.css && rm -rf public/css

            # --- Restart PM2 ---
            pm2 restart cs2d-serverlist || pm2 start npm --name cs2d-serverlist -- start
