name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Set production environment
            export NODE_ENV=production
            export PM2_APP="cs2d-serverlist"

            # Prepare deployment directory
            mkdir -p /usr/share/nginx/
            cd /usr/share/nginx/

            # Clone repo if not exists
            if [ ! -d "cs2d-serverlist/.git" ]; then
              git clone -b main https://github.com/ernestpasnik/cs2d-serverlist.git cs2d-serverlist
            fi

            cd cs2d-serverlist
            git pull origin main
            npm install --production

            # Detect main JS file dynamically
            MAIN_FILE=$(ls *.js | head -n 1)
            if [ -z "$MAIN_FILE" ]; then
              echo "No JS file found to run!"
              exit 1
            fi

            # Restart or start PM2 process in production
            if pm2 list | grep -q "$PM2_APP"; then
              pm2 restart $PM2_APP --update-env
            else
              pm2 start "$MAIN_FILE" --name "$PM2_APP" --update-env
            fi
