name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync --exclude={'public/cs2d','node_modules','.git','.github','.env'} -avzP . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/cs2d-serverlist --delete-after

      - name: Minify Assets and Restart PM2
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd /usr/share/nginx/cs2d-serverlist

            # Install uglifycss if missing
            uglifycss --version > /dev/null 2>&1 || npm install -g uglifycss

            # Install uglify-js if missing
            uglifyjs --version > /dev/null 2>&1 || npm install -g uglify-js

            # Minify CSS if exists
            if [ -f public/css/main.css ]; then
              uglifycss public/css/main.css > public/css/main.min.css
              rm public/css/main.css
            fi

            # Minify JS if any exist
            if compgen -G "public/js/*.js" > /dev/null; then
              uglifyjs public/js/*.js -o public/js/main.min.js
              find public/js -type f -name "*.js" ! -name "*.min.js" -delete
            fi

            # Restart the app
            pm2 restart cs2d-serverlist
          EOF
