name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync --exclude={'public/cs2d','node_modules','.git','.github','.env'} -avzP . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/cs2d-serverlist --delete-after

      - name: Minify Assets and Restart PM2
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd /usr/share/nginx/cs2d-serverlist
            uglifycss --version > /dev/null 2>&1 || npm install -g uglifycss
            uglifyjs --version > /dev/null 2>&1 || npm install -g uglify-js
            uglifycss public/css/main.css > public/styles.css
            rm -rf public/css
            uglifyjs public/js/*.js -o public/scripts.js
            rm -rf public/js
            pm2 restart cs2d-serverlist
          EOF
