name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup deployment tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync curl

      - name: Sync files to VPS
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '*.log' \
            ./ $SSH_USER@$SSH_HOST:/home/$SSH_USER/cs2d-serverlist/

      - name: Install dependencies, CS2D, minify CSS & restart PM2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            cd /home/$USER/cs2d-serverlist

            npm ci --omit=dev

            if [ -z "$(ls -A ./public/cs2d)" ]; then
              mkdir -p ./public/cs2d
              sudo curl -sSL https://gist.github.com/ernestpasnik/1fa721c2bf35a50d27ef13fd183882fb/raw | bash -s -- -d ./public/cs2d
            fi

            if [ -f ./public/css/main.css ]; then
              command -v uglifycss >/dev/null 2>&1 || npm install -g uglifycss
              uglifycss ./public/css/main.css > ./public/styles.css || true
              rm -rf ./public/css || true
            fi

            pm2 reload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
          EOF
