name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            DEPLOY_DIR="/var/www/cs2d-serverlist"
            PM2_APP="cs2d-serverlist"

            # Check prerequisites and stop if any missing
            for cmd in nginx node npm git redis-server; do
              if ! command -v $cmd > /dev/null; then
                echo "$cmd is not installed. Exiting."
                exit 1
              fi
            done

            # Create deployment directory
            sudo mkdir -p "$DEPLOY_DIR"
            sudo chown -R $USER:$USER "$DEPLOY_DIR"
            cd "$DEPLOY_DIR"

            # Clone repo if missing, otherwise pull latest
            if [ ! -d ".git" ]; then
              git clone --depth 1 -b main https://github.com/ernestpasnik/cs2d-serverlist.git .
            else
              git pull origin main
            fi

            # Set ownership and permissions for public folder
            NGINX_USER=$(nginx -V 2>&1 | grep -oP '(?<=--user=)[^ ]+')
            sudo chown -R $NGINX_USER:$NGINX_USER "$DEPLOY_DIR/public"
            sudo find "$DEPLOY_DIR/public" -type f -exec chmod 644 {} \;
            sudo find "$DEPLOY_DIR/public" -type d -exec chmod 755 {} \;

            # Install dependencies
            npm install --omit=dev

            # Start or reload PM2 app
            pm2 startOrReload ecosystem.config.js --env production
