name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deployment tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync curl

      - name: Sync files to VPS
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '*.log' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ $SSH_USER@$SSH_HOST:/home/$SSH_USER/cs2d-serverlist/

      - name: Install dependencies, CS2D, minify CSS & restart PM2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            DEPLOY_DIR="/home/$SSH_USER/cs2d-serverlist"
            cd "$DEPLOY_DIR"

            npm ci --omit=dev

            CS2D_DIR="$DEPLOY_DIR/public/cs2d"
            if [ -z "$(ls -A "$CS2D_DIR" 2>/dev/null)" ]; then
              mkdir -p "$CS2D_DIR"
              curl -sSL https://gist.github.com/ernestpasnik/1fa721c2bf35a50d27ef13fd183882fb/raw | bash -s -- -d "$CS2D_DIR"
            fi

            if [ -f "$DEPLOY_DIR/public/css/main.css" ]; then
              command -v uglifycss >/dev/null 2>&1 || npm install -g uglifycss
              uglifycss "$DEPLOY_DIR/public/css/main.css" > "$DEPLOY_DIR/public/styles.css" || true
              rm -rf "$DEPLOY_DIR/public/css" || true
            fi

            pm2 reload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
          EOF
