name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Deploy with SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          protocol: sftp
          server-dir: /home/ubuntu/cs2d-serverlist/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.env
            public/cs2d/**

      - name: Minify Assets and Restart PM2
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            mkdir -p /home/ubuntu/cs2d-serverlist
            cd /home/ubuntu/cs2d-serverlist
            uglifycss --version > /dev/null 2>&1 || npm install -g uglifycss
            uglifycss public/css/main.css > public/styles.css
            rm -rf public/css
            pm2 restart cs2d-serverlist || pm2 start npm --name cs2d-serverlist -- start
          EOF
