name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Deploy with SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          local_path: './'
          remote_path: /home/ubuntu/cs2d-serverlist/
          exclude: |
            .git*
            .github*
            node_modules/*
            .env
            public/cs2d/*

      - name: Post-deploy: Install CS2D & Restart PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            BASE=/home/ubuntu/cs2d-serverlist
            CS2D_DIR="$BASE/public/cs2d"

            # Install CS2D if missing
            if [ ! -d "$CS2D_DIR" ]; then
              echo "Installing CS2D..."
              mkdir -p "$CS2D_DIR"
              cd "$CS2D_DIR"
              sudo bash -c "$(curl -sSL https://gist.github.com/ernestpasnik/1fa721c2bf35a50d27ef13fd183882fb/raw)"
            else
              echo "CS2D already installed, skipping."
            fi

            # Minify CSS if needed
            if [ -f "$BASE/public/css/main.css" ]; then
              command -v uglifycss >/dev/null 2>&1 || sudo npm install -g uglifycss
              uglifycss "$BASE/public/css/main.css" > "$BASE/public/styles.css"
              rm -rf "$BASE/public/css"
            fi

            # Restart PM2
            pm2 restart cs2d-serverlist || pm2 start npm --name cs2d-serverlist -- start
            pm2 flush
            echo "Deployment complete, PM2 restarted."
