name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export NODE_ENV=production
            mkdir -p /usr/share/nginx/
            cd /usr/share/nginx/
            if [ ! -d "cs2d-serverlist/.git" ]; then
              git clone -b main https://github.com/ernestpasnik/cs2d-serverlist.git cs2d-serverlist
            fi
            cd cs2d-serverlist
            git pull origin main
            npm install --production
            nginx -t && sudo systemctl reload nginx
