name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /usr/share/nginx/cs2d-serverlist
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            cat public/css/*.css > /tmp/main.css && rm -rf public/css
            minhtml /tmp/main.css -o public/main.min.css
            cat public/js/*.js > /tmp/main.js && rm -rf public/js
            minhtml /tmp/main.js -o public/main.min.js
            npm install
            pm2 restart ecosystem.config.js --env production
