name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export NODE_ENV=production
            export PM2_APP=cs2d-serverlist

            mkdir -p /usr/share/nginx/
            cd /usr/share/nginx/

            if [ ! -d "cs2d-serverlist/.git" ]; then
              git clone -b main https://github.com/ernestpasnik/cs2d-serverlist.git cs2d-serverlist
            fi

            cd cs2d-serverlist
            git pull origin main
            npm install --production

            pm2 restart $PM2_APP --update-env
