name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Sync repo to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e

            mkdir -p ~/cs2d-serverlist

            # Fast rsync with checksum, deleting removed files
            rsync -az --info=NAME --checksum --delete \
              --exclude='.git*' \
              --exclude='.github*' \
              --exclude='node_modules/*' \
              --exclude='.env' \
              --exclude='public/cs2d/*' \
              ./ ~/cs2d-serverlist/

            # Install CS2D if missing
            if [ -z "$(ls -A ~/cs2d-serverlist/public/cs2d)" ]; then
              mkdir -p ~/cs2d-serverlist/public/cs2d
              curl -sSL https://gist.github.com/ernestpasnik/1fa721c2bf35a50d27ef13fd183882fb/raw | bash -s -- -d ~/cs2d-serverlist/public/cs2d
            fi

            # Minify CSS if exists
            if [ -f ~/cs2d-serverlist/public/css/main.css ]; then
              command -v uglifycss >/dev/null 2>&1 || npm install -g uglifycss
              uglifycss ~/cs2d-serverlist/public/css/main.css > ~/cs2d-serverlist/public/styles.css || true
              rm -rf ~/cs2d-serverlist/public/css || true
            fi

            # Restart PM2
            pm2 restart cs2d-serverlist || pm2 start npm --name cs2d-serverlist -- start
            pm2 flush
