name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # Upload files via SFTP
      - name: Deploy with SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          local_path: './'
          remote_path: /home/ubuntu/cs2d-serverlist/
          exclude: |
            .git*
            .github*
            node_modules/*
            .env
            public/cs2d/*

      # Run post-deploy commands: install CS2D if missing + restart PM2
      - name: Install CS2D if missing & restart PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu/cs2d-serverlist

            # --- Install CS2D only if missing ---
            if [ ! -d "public/cs2d" ]; then
              echo "CS2D not found. Running installation script..."
              sudo bash -c "$(curl -sSL https://gist.github.com/ernestpasnik/1fa721c2bf35a50d27ef13fd183882fb/raw)"
            else
              echo "CS2D already installed. Skipping installation."
            fi

            # --- Minify CSS ---
            if ! command -v uglifycss >/dev/null 2>&1; then
              sudo npm install -g uglifycss
            fi
            if [ -f public/css/main.css ]; then
              uglifycss public/css/main.css > public/styles.css || true
              rm -rf public/css || true
            fi

            # --- Restart PM2 ---
            pm2 restart cs2d-serverlist || pm2 start npm --name cs2d-serverlist -- start

            # --- Clean up old PM2 logs ---
            pm2 flush
            echo "Old PM2 logs cleared."
