name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            DEPLOY_DIR="/var/www/cs2d-serverlist"
            PM2_APP="cs2d-serverlist"

            sudo mkdir -p "$DEPLOY_DIR" && sudo chown -R $USER:$USER "$DEPLOY_DIR"
            cd "$DEPLOY_DIR"

            # Clone repo if missing, otherwise pull latest
            if [ ! -d ".git" ]; then
              git clone --depth 1 -b main https://github.com/ernestpasnik/cs2d-serverlist.git .
            else
              git pull origin main
            fi

            # Install dependencies and start/reload PM2
            npm install --omit=dev
            pm2 startOrReload ecosystem.config.js --env production
