name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync --exclude={'public/cs2d','node_modules','.git','.github','.env'} -avzP . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/cs2d-serverlist --delete-after

      - name: Restart PM2
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            uglifycss --version > /dev/null 2>&1 || npm install -g uglifycss &&
            uglifyjs --version > /dev/null 2>&1 || npm install -g uglify-js &&
            uglifycss public/css/main.css > public/css/main.min.css && rm public/css/main.css &&
            uglifyjs public/js/*.js -o public/js/main.min.js && rm public/js/!(*.min).js &&
            pm2 restart cs2d-serverlist
          "
