name: Deploy to cs2d.pp.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Sync repo to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            BASE=/home/ubuntu/cs2d-serverlist
            CS2D_DIR="$BASE/public/cs2d"

            mkdir -p "$BASE"

            # Fast incremental rsync using checksums
            rsync -az --checksum \
              --exclude='.git*' \
              --exclude='.github*' \
              --exclude='node_modules/*' \
              --exclude='.env' \
              --exclude='public/cs2d/*' \
              ./ "$BASE"/

            # Install CS2D if missing
            if [ -z "$(ls -A "$CS2D_DIR")" ]; then
              mkdir -p "$CS2D_DIR"
              curl -sSL https://gist.github.com/ernestpasnik/1fa721c2bf35a50d27ef13fd183882fb/raw | bash -s -- -d "$CS2D_DIR"
            fi

            # Minify CSS if exists
            CSS_FILE="$BASE/public/css/main.css"
            if [ -f "$CSS_FILE" ]; then
              command -v uglifycss >/dev/null 2>&1 || npm install -g uglifycss
              uglifycss "$CSS_FILE" > "$BASE/public/styles.css" || true
              rm -rf "$BASE/public/css" || true
            fi

            # Restart PM2
            pm2 restart cs2d-serverlist || pm2 start npm --name cs2d-serverlist -- start
            pm2 flush
